import type { Metadata } from "next";
import { Urbanist, Anek_Bangla } from "next/font/google";
import "./globals.scss";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "./Header";
import Footer from "./Footer";
import ConfigComponent from "./ConfigComponent";

const font_1 = Urbanist({ subsets: ["latin"] });
const font_2 = Anek_Bangla({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${font_1.className} ${font_2.className}`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange>
                    <ConfigComponent />
                    <div className="flex flex-col min-h-screen items-center max-w-screen-lg xl:max-w-screen-xl mx-auto">
                        <Header />
                        <div className="flex-[1] w-full">{children}</div>
                        <Footer />
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
