/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CTEsADiy0ub
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

export function ContactForm() {
    return (
        <form
            className="space-y-4 max-w-[480px] mx-auto"
            // onSubmit={e => {
            //     e.preventDefault();
            //     alert("Submitted!");
            // }}
        >
            <div className="space-y-2">
                <h2 className="text-3xl font-bold">Contact Us</h2>
                <p className="text-gray-500 dark:text-gray-400">
                    If you have any query, you can contact us via this form
                    below.
                </p>
            </div>
            <div className="space-y-4">
                <div className="space-y-2">
                    <Label htmlFor="full-name">Full name*</Label>
                    <Input
                        id="full-name"
                        placeholder="Enter your full name"
                        required
                    />
                </div>
                <div className="space-y-2">
                    <Label htmlFor="street-address">Address*</Label>
                    <Input
                        id="street-address"
                        required
                        placeholder="Enter your street address"
                    />
                </div>
                <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                        <Label htmlFor="email">Email</Label>
                        <Input
                            id="email"
                            placeholder="Enter your email"
                            type="email"
                        />
                    </div>
                    <div className="space-y-2">
                        <Label htmlFor="phone_no">Phone number*</Label>
                        <Input
                            required
                            id="phone_no"
                            placeholder="Enter your Phone no"
                        />
                    </div>
                </div>
                <div className="space-y-2">
                    <Label htmlFor="reason-short" className="capitalize">
                        Reason to contact*
                    </Label>
                    <Input
                        id="reason-short"
                        required
                        placeholder="Enter your reason to contact"
                    />
                </div>
                <div className="space-y-2">
                    <Label htmlFor="reason-long">Reason (additional)</Label>
                    <Textarea
                        id="reason-long"
                        rows={5}
                        placeholder="You can describe you reason furthermore"></Textarea>
                </div>
                <div className="pt-2">
                    <Button type="submit">Submit</Button>
                </div>
            </div>
        </form>
    );
}
