// import principal from "@/assets/principal.jpg";
// import { faker } from "@faker-js/faker";

// export const teachers = Array(45)
//     .fill({
//         name: "প্রফেসর মোঃ আবদুর রউফ",
//         nameEn: "PROFESSOR MD. ABDUR RAOUF",
//         post: "অধ্যক্ষ",
//         subject: "ব্যবস্থাপনা",
//         birthday: "01-01-1968",
//         id: "7698",
//         uid: 1,
//         phone_no: "01712432359",
//         photoURL: principal.src,
//     })
//     .map((teacher, i) => {
//         const t = { ...teacher };
//         t.uid += i;
//         t.name = faker.person.fullName();
//         t.nameEn = t.name;
//         t.birthday = faker.date.past().toISOString().split("T")[0];
//         t.phone_no = faker.string.numeric(10);
//         t.photoURL = faker.image.avatar();
//         t.post = faker.person.jobTitle();
//         t.subject = faker.person.jobType();
//         return t;
//     });

// console.log(teachers);

export const teachers = [
    {
        name: "Dawn Effertz",
        nameEn: "Dawn Effertz",
        post: "Central Tactics Executive",
        subject: "Designer",
        birthday: "2023-05-16",
        id: "7698",
        uid: 1,
        phone_no: "2813786086",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/59.jpg",
    },
    {
        name: "Rosemarie Labadie",
        nameEn: "Rosemarie Labadie",
        post: "Product Branding Architect",
        subject: "Executive",
        birthday: "2023-04-12",
        id: "7698",
        uid: 2,
        phone_no: "2475687716",
        photoURL: "https://avatars.githubusercontent.com/u/74438498",
    },
    {
        name: "Danny Metz",
        nameEn: "Danny Metz",
        post: "Corporate Web Representative",
        subject: "Representative",
        birthday: "2023-06-07",
        id: "7698",
        uid: 3,
        phone_no: "8975319139",
        photoURL: "https://avatars.githubusercontent.com/u/49776345",
    },
    {
        name: "Mr. Angel Dach",
        nameEn: "Mr. Angel Dach",
        post: "Legacy Identity Assistant",
        subject: "Liaison",
        birthday: "2023-12-15",
        id: "7698",
        uid: 4,
        phone_no: "7364852963",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1082.jpg",
    },
    {
        name: "Enrique Willms",
        nameEn: "Enrique Willms",
        post: "Central Integration Producer",
        subject: "Officer",
        birthday: "2023-05-27",
        id: "7698",
        uid: 5,
        phone_no: "7992355439",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1083.jpg",
    },
    {
        name: "Ms. Lee Waelchi",
        nameEn: "Ms. Lee Waelchi",
        post: "Regional Program Officer",
        subject: "Developer",
        birthday: "2023-10-04",
        id: "7698",
        uid: 6,
        phone_no: "6814441949",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/218.jpg",
    },
    {
        name: "Jimmie Watsica",
        nameEn: "Jimmie Watsica",
        post: "Legacy Infrastructure Orchestrator",
        subject: "Producer",
        birthday: "2023-04-04",
        id: "7698",
        uid: 7,
        phone_no: "5220405438",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1144.jpg",
    },
    {
        name: "Cesar Marvin",
        nameEn: "Cesar Marvin",
        post: "Investor Configuration Liaison",
        subject: "Agent",
        birthday: "2023-09-28",
        id: "7698",
        uid: 8,
        phone_no: "4302786217",
        photoURL: "https://avatars.githubusercontent.com/u/75492139",
    },
    {
        name: "Frederick Buckridge",
        nameEn: "Frederick Buckridge",
        post: "Internal Branding Administrator",
        subject: "Assistant",
        birthday: "2024-03-04",
        id: "7698",
        uid: 9,
        phone_no: "8894762376",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/679.jpg",
    },
    {
        name: "Rosie Ritchie",
        nameEn: "Rosie Ritchie",
        post: "Human Assurance Agent",
        subject: "Representative",
        birthday: "2023-11-18",
        id: "7698",
        uid: 10,
        phone_no: "0551478666",
        photoURL: "https://avatars.githubusercontent.com/u/26320714",
    },
    {
        name: "Mr. Ernest Kozey",
        nameEn: "Mr. Ernest Kozey",
        post: "Global Accountability Strategist",
        subject: "Producer",
        birthday: "2023-04-15",
        id: "7698",
        uid: 11,
        phone_no: "3119639793",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1105.jpg",
    },
    {
        name: "Levi Parisian",
        nameEn: "Levi Parisian",
        post: "Future Division Planner",
        subject: "Liaison",
        birthday: "2024-03-22",
        id: "7698",
        uid: 12,
        phone_no: "1617290249",
        photoURL: "https://avatars.githubusercontent.com/u/79875591",
    },
    {
        name: "Annie Schiller",
        nameEn: "Annie Schiller",
        post: "Internal Program Coordinator",
        subject: "Officer",
        birthday: "2023-12-20",
        id: "7698",
        uid: 13,
        phone_no: "3188748518",
        photoURL: "https://avatars.githubusercontent.com/u/36933793",
    },
    {
        name: "Bennie Roberts",
        nameEn: "Bennie Roberts",
        post: "Human Integration Assistant",
        subject: "Representative",
        birthday: "2023-09-28",
        id: "7698",
        uid: 14,
        phone_no: "0756741113",
        photoURL: "https://avatars.githubusercontent.com/u/12405241",
    },
    {
        name: "Matthew Buckridge",
        nameEn: "Matthew Buckridge",
        post: "District Identity Developer",
        subject: "Agent",
        birthday: "2023-07-09",
        id: "7698",
        uid: 15,
        phone_no: "8191430995",
        photoURL: "https://avatars.githubusercontent.com/u/33826256",
    },
    {
        name: "Russell Russel",
        nameEn: "Russell Russel",
        post: "Principal Operations Engineer",
        subject: "Strategist",
        birthday: "2023-09-25",
        id: "7698",
        uid: 16,
        phone_no: "6059598277",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/681.jpg",
    },
    {
        name: "Toni Greenholt-Windler III",
        nameEn: "Toni Greenholt-Windler III",
        post: "International Metrics Agent",
        subject: "Associate",
        birthday: "2023-08-13",
        id: "7698",
        uid: 17,
        phone_no: "2050272883",
        photoURL: "https://avatars.githubusercontent.com/u/15543061",
    },
    {
        name: "Iris D'Amore",
        nameEn: "Iris D'Amore",
        post: "Chief Tactics Agent",
        subject: "Analyst",
        birthday: "2023-09-08",
        id: "7698",
        uid: 18,
        phone_no: "8253326375",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/621.jpg",
    },
    {
        name: "Guillermo Bahringer Jr.",
        nameEn: "Guillermo Bahringer Jr.",
        post: "Customer Accountability Representative",
        subject: "Designer",
        birthday: "2023-09-25",
        id: "7698",
        uid: 19,
        phone_no: "2866947111",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/774.jpg",
    },
    {
        name: "Wilfred Lynch-Wiegand",
        nameEn: "Wilfred Lynch-Wiegand",
        post: "International Optimization Designer",
        subject: "Associate",
        birthday: "2023-09-09",
        id: "7698",
        uid: 20,
        phone_no: "1023990607",
        photoURL: "https://avatars.githubusercontent.com/u/4038745",
    },
    {
        name: "Marlene Beier",
        nameEn: "Marlene Beier",
        post: "Global Metrics Assistant",
        subject: "Coordinator",
        birthday: "2024-03-17",
        id: "7698",
        uid: 21,
        phone_no: "0695249388",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/788.jpg",
    },
    {
        name: "Micheal Rempel",
        nameEn: "Micheal Rempel",
        post: "National Response Director",
        subject: "Producer",
        birthday: "2023-10-30",
        id: "7698",
        uid: 22,
        phone_no: "9022330698",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/670.jpg",
    },
    {
        name: "Tami Ratke",
        nameEn: "Tami Ratke",
        post: "Direct Accountability Assistant",
        subject: "Engineer",
        birthday: "2024-01-22",
        id: "7698",
        uid: 23,
        phone_no: "8766792792",
        photoURL: "https://avatars.githubusercontent.com/u/41973463",
    },
    {
        name: "Kelly Heaney",
        nameEn: "Kelly Heaney",
        post: "Legacy Brand Supervisor",
        subject: "Liaison",
        birthday: "2023-08-09",
        id: "7698",
        uid: 24,
        phone_no: "4263718752",
        photoURL: "https://avatars.githubusercontent.com/u/97886149",
    },
    {
        name: "Peter Hoppe",
        nameEn: "Peter Hoppe",
        post: "Customer Integration Analyst",
        subject: "Facilitator",
        birthday: "2023-08-04",
        id: "7698",
        uid: 25,
        phone_no: "9341571131",
        photoURL: "https://avatars.githubusercontent.com/u/93314523",
    },
    {
        name: "Erik Zieme DVM",
        nameEn: "Erik Zieme DVM",
        post: "National Implementation Assistant",
        subject: "Engineer",
        birthday: "2023-05-30",
        id: "7698",
        uid: 26,
        phone_no: "2725912457",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/383.jpg",
    },
    {
        name: "Miss Nichole Will",
        nameEn: "Miss Nichole Will",
        post: "Lead Accountability Liaison",
        subject: "Technician",
        birthday: "2023-06-26",
        id: "7698",
        uid: 27,
        phone_no: "6119452961",
        photoURL: "https://avatars.githubusercontent.com/u/64901396",
    },
    {
        name: "Olive Bailey",
        nameEn: "Olive Bailey",
        post: "Central Solutions Engineer",
        subject: "Coordinator",
        birthday: "2024-03-17",
        id: "7698",
        uid: 28,
        phone_no: "3590371002",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/889.jpg",
    },
    {
        name: "Paulette Franecki",
        nameEn: "Paulette Franecki",
        post: "District Research Planner",
        subject: "Developer",
        birthday: "2023-05-03",
        id: "7698",
        uid: 29,
        phone_no: "3150760491",
        photoURL: "https://avatars.githubusercontent.com/u/40938316",
    },
    {
        name: "Suzanne Satterfield",
        nameEn: "Suzanne Satterfield",
        post: "Lead Web Director",
        subject: "Orchestrator",
        birthday: "2023-09-12",
        id: "7698",
        uid: 30,
        phone_no: "8559236969",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/681.jpg",
    },
    {
        name: "Marilyn Simonis",
        nameEn: "Marilyn Simonis",
        post: "Global Functionality Architect",
        subject: "Designer",
        birthday: "2023-04-20",
        id: "7698",
        uid: 31,
        phone_no: "7275770966",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/759.jpg",
    },
    {
        name: "Elvira Grady Jr.",
        nameEn: "Elvira Grady Jr.",
        post: "Customer Data Strategist",
        subject: "Agent",
        birthday: "2024-03-25",
        id: "7698",
        uid: 32,
        phone_no: "5223330795",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/900.jpg",
    },
    {
        name: "Jessie Marquardt",
        nameEn: "Jessie Marquardt",
        post: "Legacy Operations Director",
        subject: "Director",
        birthday: "2024-01-21",
        id: "7698",
        uid: 33,
        phone_no: "6038779243",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/793.jpg",
    },
    {
        name: "Mr. Tyler Sipes",
        nameEn: "Mr. Tyler Sipes",
        post: "Senior Markets Orchestrator",
        subject: "Liaison",
        birthday: "2023-05-31",
        id: "7698",
        uid: 34,
        phone_no: "5503538541",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/82.jpg",
    },
    {
        name: "Felix Hettinger",
        nameEn: "Felix Hettinger",
        post: "Human Identity Director",
        subject: "Designer",
        birthday: "2023-08-23",
        id: "7698",
        uid: 35,
        phone_no: "4391691392",
        photoURL: "https://avatars.githubusercontent.com/u/1826316",
    },
    {
        name: "Sherri Pagac",
        nameEn: "Sherri Pagac",
        post: "Senior Web Technician",
        subject: "Officer",
        birthday: "2023-07-26",
        id: "7698",
        uid: 36,
        phone_no: "6672040484",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/902.jpg",
    },
    {
        name: "Wendy Vandervort",
        nameEn: "Wendy Vandervort",
        post: "Regional Marketing Planner",
        subject: "Liaison",
        birthday: "2023-08-05",
        id: "7698",
        uid: 37,
        phone_no: "6617950271",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/632.jpg",
    },
    {
        name: "Regina Simonis",
        nameEn: "Regina Simonis",
        post: "Chief Usability Supervisor",
        subject: "Specialist",
        birthday: "2023-12-21",
        id: "7698",
        uid: 38,
        phone_no: "1462531773",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/944.jpg",
    },
    {
        name: "Lora Quitzon",
        nameEn: "Lora Quitzon",
        post: "Internal Data Manager",
        subject: "Planner",
        birthday: "2023-10-19",
        id: "7698",
        uid: 39,
        phone_no: "0442721481",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/235.jpg",
    },
    {
        name: "Valerie Parisian",
        nameEn: "Valerie Parisian",
        post: "Principal Response Supervisor",
        subject: "Supervisor",
        birthday: "2023-12-15",
        id: "7698",
        uid: 40,
        phone_no: "6271205995",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/131.jpg",
    },
    {
        name: "Marjorie Price",
        nameEn: "Marjorie Price",
        post: "Forward Interactions Associate",
        subject: "Manager",
        birthday: "2024-02-07",
        id: "7698",
        uid: 41,
        phone_no: "8405731239",
        photoURL: "https://avatars.githubusercontent.com/u/46085783",
    },
    {
        name: "Brandon Hilpert",
        nameEn: "Brandon Hilpert",
        post: "Human Marketing Administrator",
        subject: "Executive",
        birthday: "2023-10-25",
        id: "7698",
        uid: 42,
        phone_no: "1873491071",
        photoURL:
            "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/844.jpg",
    },
    {
        name: "Jack Mosciski",
        nameEn: "Jack Mosciski",
        post: "Chief Data Facilitator",
        subject: "Agent",
        birthday: "2024-02-21",
        id: "7698",
        uid: 43,
        phone_no: "0185056081",
        photoURL: "https://avatars.githubusercontent.com/u/56366341",
    },
    {
        name: "Melody Dietrich",
        nameEn: "Melody Dietrich",
        post: "Direct Tactics Administrator",
        subject: "Planner",
        birthday: "2023-11-23",
        id: "7698",
        uid: 44,
        phone_no: "0822836938",
        photoURL: "https://avatars.githubusercontent.com/u/38515888",
    },
    {
        name: "Lucia Huel-Skiles Sr.",
        nameEn: "Lucia Huel-Skiles Sr.",
        post: "Regional Configuration Producer",
        subject: "Strategist",
        birthday: "2023-11-18",
        id: "7698",
        uid: 45,
        phone_no: "2802140608",
        photoURL: "https://avatars.githubusercontent.com/u/45170821",
    },
];
